version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: maradona
      MYSQL_USER: maradona
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/maradona.sql:/docker-entrypoint-initdb.d/init.sql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - red
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
      - red

  api:
    build: api/.
    container_name: api
    environment:
      DATABASE: "db"
    links:
      - db
    restart: always
    ports:
      - "5000:5000"
    networks:
      - red

  app:
    build: app/.
    container_name: app
    environment:
      TOKEN_TELEGRAM: "1502753352:AAFKgU0Jy84oEjiH9qmFtYdZmOMunbcNn-s"
      CHAT_ID: "390771484"
      MINUTES: "1" # CADA CUANTOS MINUTOS
      SERVER: "api" # SERVIDOR API
    links:
      - api
    restart: always
    networks:
      - red
volumes:
  dbdata:
  config:
networks:
  red:
    driver: bridge

