apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    USE maradona;
    DROP TABLE IF EXISTS `frases`;

    CREATE TABLE `frases` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `frase` varchar(1000) NOT NULL,
      `detalle` varchar(1000) NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

    LOCK TABLES `frases` WRITE;
    /*!40000 ALTER TABLE `frases` DISABLE KEYS */;

    INSERT INTO `frases` (`id`, `frase`, `detalle`)
    VALUES
      (1,'Yo me equivoqué y pagué, pero la pelota no se mancha','Una frase célebre, en una Bombonera llena durante el partido de su despedida del fútbol.'),
      (2,'Fue la mano de Dios','Así patentó la célebre frase, cuando en el Mundial de México 1986 le hizo a Inglaterra un gol con la mano.');

    /*!40000 ALTER TABLE `frases` ENABLE KEYS */;
    UNLOCK TABLES;
