apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app-deployment
  namespace: maradona
spec:
  selector:
    matchLabels:
      app: app-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - image: safernandez666/maradona_app:latest
        name: app
        env:
        - name: TOKEN_TELEGRAM
          valueFrom:
            secretKeyRef:
              name: tokentelegram
              key: token
        - name: CHAT_ID
          valueFrom:
            secretKeyRef:
              name: chatid
              key: token
        - name: MINUTES
          value: '5'
        - name: SERVER
          value: 'api-service'
        imagePullPolicy: Always
